const ALERT = 'ALERT' ;
const REFRETCH_CHATS = 'REFETCH_CHATS' ;

const NEW_ATTACHMENT = 'NEW_ATTACHMENT' ;

const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'
const NEW_MESSAGE = 'NEW_MESSAGE' 

const NEW_REQUEST = 'NEW_REQUEST'
const START_TYPING = 'START_TYPING'
const STOP_TYPING = 'STOP_TYPING'
const DELETE_MESSAGE = 'DELETE_MESSAGE'

export {ALERT ,NEW_REQUEST , DELETE_MESSAGE , REFRETCH_CHATS ,  NEW_ATTACHMENT ,NEW_MESSAGE, NEW_MESSAGE_ALERT , START_TYPING , STOP_TYPING}