const ALERT = 'ALERT' ;
const REFRETCH_CHATS = 'REFETCH_CHATS' ;

const NEW_ATTACHMENT = 'NEW_ATTACHMENT' ;
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'

export {ALERT , REFRETCH_CHATS ,  NEW_ATTACHMENT , NEW_MESSAGE_ALERT}